### ISSUE TITLE
TagsWidget should decodeEntities for tags with special characters

### ISSUE THREAD

**Issue by fatcrobat** [codefog/tags-bundle#11]
Hey there,

if you use the following example Tag `BITKOM (Arbeitskreis ITK-Vertrags- und Rechtsgestaltung)` that contains brakets the generated tag text will contain encoded html entities `BITKOM &#40;Arbeitskreis ITK-Vertrags- und Rechtsgestaltung&#41;` inside the selectize input. 

In TagsWidget::generateAllTags decode entities should do the trick:

```
/**
     * Generate all tags.
     *
     * @param CollectionInterface $tags
     *
     * @return array
     */
    private function generateAllTags(CollectionInterface $tags): array
    {
        $return = [];

        /** @var Tag $tag */
        foreach ($tags as $tag) {
            $return[] = ['value' => $tag->getValue(), 'text' => \StringUtil::decodeEntities($tag->getName())];
        }

        return $return;
    }
```

**Comment by qzminski** [comment]
Fixed in a3af6d6.
