### ISSUE TITLE
Database Error after Installation

### ISSUE THREAD

**Issue by oliverkieslich** [codefog/tags-bundle#12]
Hi,

it looks like a great module so far. But:

I am running on 
Contao 4.4.13.
PHP 7.1.
codefog/contao-haste 4.18.1
codefog/tags-bundle 2.10

Contao and both modules were installed with the "contao manager".
Database-Update and Cache refresh has been done.
No errors appeared during installation.

When I want to use the tags within contao, no tags input field appears in articles, evens, news, etc. 
And when I enter the tag module and want to add a new tag, this error appears:

An exception occurred while executing 'INSERT INTO tl_cfg_tag (`tstamp`) VALUES (0)': SQLSTATE[HY000]: General error: 1364 Field 'alias' doesn't have a default value

I´ve given the field a default value by my own directly within the database table. Then the error doesn't appear any more. But I can't add a new tag, because the "source" pulldown is without any content. 
And the tags input field still doesn't appear anywhere in contao.

Do you have any idea about this issues?

Thank you very much

Oliver

**Comment by qzminski** [comment]
Thanks for reporting the SQL issue, I have just fixed it.

The bundle does not provide any tagging functionality by default, as clearly stated in the README file.
