### ISSUE TITLE
findByPk in DefaultManager::find() leads to UNIQUE error for name and source

### ISSUE THREAD

**Issue by Defcon0** [codefog/tags-bundle#13]
Hello,

I want to store new tags using `DefaultManager::saveDcaField()` (`$value` is `serialize(['text1', 'text2'])` for example). In this function we have:

```
public function saveDcaField(string $value, DataContainer $dc): string
    {
        $value = StringUtil::deserialize($value, true);
        $criteria = $this->getCriteria();

        /** @var array $value */
        foreach ($value as $k => $v) {
            if ($this->find($v, $criteria) !== null) {
                continue;
            }

            $value[$k] = $this->createTag($v)->getValue();
        }
// ...
```

Here `DefaultManager::find()` is called leading to this:

```
/** @var TagModel $adapter */
        $adapter = $this->framework->getAdapter(TagModel::class);

        if (($model = $adapter->findByPk($value)) === null) {
            return null;
        }
// ...
```

As you can see, `$value` is some text and it's passed to `findByPk()`. In `TagsModel` "pk" is not overridden with some textual field, so it's the ordinary numeric id which finally leads to the `$model` not being found. Then `$this->createTag()` is called which produces the UNIQUE error.

Shouldn't it be findByName in `DefaultManager::find()`?

Bye Defcon0

**Comment by qzminski** [comment]
Obsolete due to version 3.0.
