### ISSUE TITLE
Tags Configuration

### ISSUE THREAD

**Issue by dabasti** [codefog/tags-bundle#14]
Hallo codefog team,

ich habe gerade versucht anhand der doku das Plugin zu kofigurieren.
Ich bin dazu folgendermaßen vorgegangen:
Ordner angelegt: 
- app/Resources/contao/config
- app/Resources/contao/dca
- app/Resources/contao/languages

Dateien angelegt:
- app/Resources/contao/config/config.yml
- app/Resources/contao/dca/tl_app_article.php
- app/Resources/contao/languages/de/tl_cfg_tags.php

Leider wirft mir der contao manager beim aufbau des Caches folgenden Fehler:
`Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) `
für die Datei` tl_app_article.php` auf Zeile 5 (`'label'     => &$GLOBALS['TL_LANG']['tl_app_article']['tags'],`)

Wo habe ich einen Fehler gemacht?

**Comment by qzminski** [comment]
Sorry, I do not speak German. Please describe your issue in English.

**Comment by dabasti** [comment]
Allright sorry :)

i tried to configurate the plugin as described in the documentation.
I proceeded as follows:

Create Folders:

- app/Resources/contao/config
- app/Resources/contao/dca
- app/Resources/contao/languages

Create Files:

- app/Resources/contao/config/config.yml
- app/Resources/contao/dca/tl_app_article.php
- app/Resources/contao/languages/de/tl_cfg_tags.php

Unfortunately contao throws an error while rebuilding the Cache in the contao manager:
`Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW)`
for the file `tl_app_article.php` on line 5 (`'label' => &$GLOBALS['TL_LANG']['tl_app_article']['tags'],`)

What did i do wrong?

Thanks :)

**Comment by qzminski** [comment]
You have a syntax error in your own custom PHP file. That does not seem to be a problem of bundle itself.
