### ISSUE TITLE
Adding tags with leading number(s) will fail

### ISSUE THREAD

**Issue by qzminski** [codefog/tags-bundle#18]
From https://github.com/terminal42/contao-node/issues/10:

> I've tried to add some new content-node tags and run into a problem.
> 
> An exception occurred while executing 'INSERT INTO tl_cfg_tag_node (node_id, cfg_tag_id) VALUES ('38', '4-3s')': SQLSTATE[01000]: Warning: 1265 Data truncated for column 'cfg_tag_id' at row 1
> 
> I added something like this: 4-3s, but I also tried 2-grid etc. Seems, that leading numbers cause some insert problems.
> 
> Best regards,
> Sares

**Comment by qzminski** [comment]
@saress please update the bundle to 2.1.4 and your problem should be fixed.

**Comment by saress** [comment]
Hi Qzminski,

great, thank you very much. I have updated the bundle and it works fine now :-)
