### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by saress** [codefog/tags-bundle#19]
From: 
https://github.com/terminal42/contao-node/issues/9#issuecomment-515322562
https://github.com/terminal42/contao-node/issues/9#issuecomment-515325570

> @qzminski: I have just recognized, that it also happens if I add a new entry:
> 
> `An exception occurred while executing 'INSERT INTO tl_cfg_tag (`tstamp`, `name`, `source`) VALUES (1564121831, 'content', 'terminal42_node')': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry `
> 
> I guess, it is related to the tags-bundle, right?
> I will reference it here also: https://github.com/codefog/tags-bundle
> 
> Thanks!

**Comment by qzminski** [comment]
What are the exact steps do reproduce this issue? Can you list point-by-point what I should do to reproduce? I tried copying a node and save it but no error came up.
