### ISSUE TITLE
Alias is not generated if I just assign a tag

### ISSUE THREAD

**Issue by Defcon0** [codefog/tags-bundle#21]
Hello,

if I assign a *new* tag to a news for example, the alias is not generated. This just is done when I'm editing the alias directly.

Would it be possible to add this functionality?

Bye Defcon0

**Comment by qzminski** [comment]
What alias is not generated? The news alias?

**Comment by Defcon0** [comment]
The tag's alias :-)

**Comment by qzminski** [comment]
@Defcon0 would you mind testing a0f1e73 please?

**Comment by qzminski** [comment]
3.1.0 stable released :+1:
