### ISSUE TITLE
Select Widget collides with other JS enhanced widgets

### ISSUE THREAD

**Issue by bezin** [codefog/tags-bundle#22]
Hi there, 

the selectize widget collides with the calendar widget due to the stacking context.

<img width="433" alt="Calendar widget overlays selectize widget" src="https://user-images.githubusercontent.com/4400435/84484762-7c16d180-ac9b-11ea-9123-1f7db20e87fa.png">

This CSS fixes it: 
```
.cfg-tags {
  position: relative;
  z-index: 0;
}
```

**Comment by qzminski** [comment]
Should be fixed in 3.1.1 :+1:
