### ISSUE TITLE
Retrieve data in Model using getRelated()

### ISSUE THREAD

**Issue by valentin-** [codefog/tags-bundle#23]
Hi, thanks for the awesome extension!

I'm trying to retrieve the related tag-data of the model inside a controller, but the result is empty.

Here is the output of the Model:

![image](https://user-images.githubusercontent.com/90033/90331971-228f9380-dfb9-11ea-9abe-0970767ee2f4.png)

Is it possible to get the tag data with getRelated() or is it only available using the TagFinder?

![image](https://user-images.githubusercontent.com/90033/90332008-7306f100-dfb9-11ea-8032-34cddcfd5722.png)
![image](https://user-images.githubusercontent.com/90033/90332139-c75ea080-dfba-11ea-841e-1dae4562dc3c.png)

Thanks!

**Comment by qzminski** [comment]
Unfortunately, it is not possible to fetch the tags using `getRelated()` method as it is not supported neither by `haste-ManyToMany` relationship, nor by this tags extension. To retrieve the tags you always have to use a tag finder.
