### ISSUE TITLE
Multiline style issue

### ISSUE THREAD

**Issue by Defcon0** [codefog/tags-bundle#27]
Hello,

tested on contao 4.9: when having multiple lines of tags in the widget, the select field shouldn't have height set to 30px (comes from the css class `tl_select` in `basic.css` from contao, but `height: auto;`.

See screenshot:

![screen](https://user-images.githubusercontent.com/1485098/121693892-d5d9f380-cac9-11eb-8d58-d6d62d490786.png)

I could do a PR for that one. Are you ok with it? I'd create a css file in src/Resources/assets/css/cfg-tags-bundle.css adding:

```
.bootstrap-tagsinput.tl_select {
  height. auto;
}
```

and add it in a `loadDataContainer` listener where I check for the backend context.

OK?

Bye Defcon0

**Comment by qzminski** [comment]
Good catch, please create a pull request. I think it should be sufficient to add this code here: https://github.com/codefog/tags-bundle/blob/master/src/Resources/public/backend.css

**Comment by Defcon0** [comment]
PR has been created: https://github.com/codefog/tags-bundle/pull/28

**Comment by qzminski** [comment]
Sorry, are you using a select field, instead of the tags wizard?

**Comment by Defcon0** [comment]
Arrgh, sorry. It was another widget looking nearly the same. Sorry for the confusion, I'll delete the PR.
