### ISSUE TITLE
Type error in list view if tags are a filter

### ISSUE THREAD

**Issue by koertho** [codefog/tags-bundle#34]
I get an type error in backend list view, when there is also a tag filter. The options callback is called, but the dc object has an empy field propery here: https://github.com/codefog/tags-bundle/blob/77a509172877088d5461e25b4ea073cc2c09868e/src/EventListener/TagManagerListener.php#L96

There should be at least an additional check, if the value is empty or GET contains 'edit'.

![image](https://user-images.githubusercontent.com/12064642/167076837-3676ca0f-6e94-4088-bd1b-334398daf592.png)

**Comment by qzminski** [comment]
Should be fixed in 3.3.4.
